---
title: C6320 | Документация Майкрософт
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 1d37a8d33f756372cd0448e94cf9f6d5e2408cf1
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/15/2020
ms.locfileid: "77273421"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

предупреждение C6320: выражение фильтра исключений является константой EXCEPTION_EXECUTE_HANDLER. Это может маскировать исключения, которые не предназначены для обработки  
  
 Это предупреждение указывает на побочный результат использования EXCEPTION_EXECUTE_HANDLERной константы в блоке __except. В этом случае инструкция в блоке _except \_будет всегда выполняться для устранения исключения, включая исключения, которые не нужно выполнять в определенной функции. Рекомендуется проверять исключение перед его обработкой.  
  
## <a name="example"></a>Пример  
 В следующем коде создается это предупреждение, поскольку блок __except будет пытаться обменять исключения всех типов:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Чтобы устранить это предупреждение, используйте `GetExceptionCode` для проверки конкретного исключения перед его обработкой, как показано в следующем коде:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>См. также  
 [Оператор try-except](https://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)
