---
title: C26112
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26112
helpviewer_keywords:
- C26112
ms.assetid: 926de738-b9b0-43d7-9137-ab2daa44ad4d
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3178b0f67828ceb9e7a7161722d10e4ce6b29203
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/16/2019
ms.locfileid: "72450299"
---
# <a name="c26112"></a>C26112
предупреждение C26112: вызывающий объект не может удерживать блокировки перед вызовом \<func >.

 Заметка `_Requires_no_locks_held_` накладывает предусловие, что вызывающий объект не должен удерживать никакой блокировки при вызове функции. Предупреждение C26112 выдается, когда функция не может освободить все блокировки перед вызовом другой функции.

## <a name="example"></a>Пример
 В следующем примере создается предупреждение C26112, так как предусловие `_Requires_no_locks_held_` нарушается вызовом `NoLocksAllowed` в разделе заблокировано.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
} DATA;

_Requires_no_locks_held_

void NoLocksAllowed(DATA* p)
{
     // Lock sensitive operations here
}

void LocksHeldFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    NoLocksAllowed(p); // Warning C26112
    LeaveCriticalSection(&p->cs);
}
```
