---
title: C26112
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26112
helpviewer_keywords:
- C26112
ms.assetid: 926de738-b9b0-43d7-9137-ab2daa44ad4d
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: cba2d0f6947af6506371ae1da93ccae025e5bdb0
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/06/2019
ms.locfileid: "74879182"
---
# <a name="c26112"></a>C26112
предупреждение C26112: вызывающий объект не может удерживать блокировки перед вызовом \<Func >.

 Заметка `_Requires_no_locks_held_` накладывает предусловие, что вызывающий объект не должен удерживать никакой блокировки при вызове функции. Предупреждение C26112 выдается, когда функция не может освободить все блокировки перед вызовом другой функции.

## <a name="example"></a>Пример
 В следующем примере создается предупреждение C26112, так как предусловие `_Requires_no_locks_held_` нарушается вызовом `NoLocksAllowed` в разделе заблокировано.

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
} DATA;

_Requires_no_locks_held_

void NoLocksAllowed(DATA* p)
{
     // Lock sensitive operations here
}

void LocksHeldFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    NoLocksAllowed(p); // Warning C26112
    LeaveCriticalSection(&p->cs);
}
```
