---
title: C26112
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26112
helpviewer_keywords:
- C26112
ms.assetid: 926de738-b9b0-43d7-9137-ab2daa44ad4d
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 0a252c857b250b767638dbb38e6aac9c50b72b44
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/15/2020
ms.locfileid: "77270800"
---
# <a name="c26112"></a>C26112
предупреждение C26112: вызывающий объект не может удерживать блокировки перед вызовом \<Func >.

 Заметка `_Requires_no_locks_held_` накладывает предусловие, что вызывающий объект не должен удерживать никакой блокировки при вызове функции. Предупреждение C26112 выдается, когда функция не может освободить все блокировки перед вызовом другой функции.

## <a name="example"></a>Пример
 В следующем примере создается предупреждение C26112, так как предусловие `_Requires_no_locks_held_` нарушается вызовом `NoLocksAllowed` в разделе заблокировано.

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
} DATA;

_Requires_no_locks_held_

void NoLocksAllowed(DATA* p)
{
     // Lock sensitive operations here
}

void LocksHeldFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    NoLocksAllowed(p); // Warning C26112
    LeaveCriticalSection(&p->cs);
}
```
