---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 668c1104cde1a39896082b8877e7b6c3b10ad23c
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/23/2019
ms.locfileid: "62574476"
---
# <a name="c28198"></a>C28198
Предупреждение C28198: Возможна утечка памяти вследствие исключения.

 Это предупреждение указывает, что выделенная память не освобождается после возникновения исключения. Инструкции в конце пути может вызвать исключение. Объем памяти был передан на функцию, которая будет сохранена копия освобождаемой позже.

 Это предупреждение очень похож на "Предупреждение" [C28197](../code-quality/c28197.md). Заметки, которые рекомендуются для использования с предупреждением [C28197](../code-quality/c28197.md) также может использоваться здесь.

## <a name="example"></a>Пример
 Следующий пример кода вызывает появление этого предупреждения.

```
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 Следующий пример кода позволяет избежать появления этого предупреждения.

```
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```